### ISSUE TITLE
TypeError: distCoeffs2 is not a numpy array, neither a scalar

### ISSUE THREAD

**Issue by alphamarket** [erget/StereoVision#11]
Trying to calibrate a couple of stereo cameras, I am encountering the following error
![image](https://cloud.githubusercontent.com/assets/2348936/17463561/9717863a-5cdd-11e6-97cb-b5efa63e1e0a.png)

The [code snap](https://github.com/noise2/stereo_depth/blob/master/play.py#L48-L70) fetched from the [this](https://erget.wordpress.com/2014/02/28/calibrating-a-stereo-pair-with-python/) article.

> **Other thing:** I installed the StereoVIsion via `pip install StereoVision` but after I encountered the following error on the same code snap(mentioned above) I compared the installed codes in my system and the one on Github and noticed my installation is no updated so I have updated(replaced) them with the one on Github.
> ![image](https://cloud.githubusercontent.com/assets/2348936/17463596/5971ec5c-5cde-11e6-8c87-faed4313c6d1.png)
### My Question:

What is wrong with it?

---

P.S: I have successfully calibrated the OpenCV's standard [left/right images](https://github.com/opencv/opencv/blob/master/samples/data) using the following codes:

``` PYTHON
calibrator = StereoCalibrator(9, 6, 2, (480, 640))
for idx in range(1, 14):
    calibrator.add_corners((cv2.imread('images/left%02d.jpg' %idx), cv2.imread('images/right%02d.jpg' %idx)))

calibration = calibrator.calibrate_cameras()
print "Calibation error:", calibrator.check_calibration(calibration)
calibration.export(calib_dir)
```

But after I have updated the codes, I am getting following error
![image](https://cloud.githubusercontent.com/assets/2348936/17463622/f79c71c2-5cde-11e6-910f-717f80e89da1.png)

**Comment by noise2** [comment]
I have found the problem, I was sending both stereo cameras' frame size as a tuple to `StereoCalibrator` after I have correct it, I am getting the following error:
```
OpenCV Error: Assertion failed (nimages > 0 && nimages == (int)imagePoints1.total() && (!imgPtMat2 || nimages == (int)imagePoints2.total())) in collectCalibrationData, file /home/dariush/Desktop/opencv-2.4.13/modules/calib3d/src/calibration.cpp, line 3164
Traceback (most recent call last):
  File "./play.py", line 76, in <module>
    execute_calibration(cameras);
  File "./play.py", line 66, in execute_calibration
    calibration = calibrator.calibrate_cameras()
  File "/usr/local/lib/python2.7/dist-packages/stereovision/calibration.py", line 233, in calibrate_cameras
    flags=flags)[1:]
cv2.error: /home/dariush/Desktop/opencv-2.4.13/modules/calib3d/src/calibration.cpp:3164: error: (-215) nimages > 0 && nimages == (int)imagePoints1.total() && (!imgPtMat2 || nimages == (int)imagePoints2.total()) in function collectCalibrationData
```
while trying to `calibrator.calibrate_cameras()`, why this?
