### ISSUE TITLE
show_webcams command gives error 

### ISSUE THREAD

**Issue by santhoshrsk** [erget/StereoVision#17]
I installed StereoVision using pip and tried to run show_webcams device0 device1, it is giving cv2.error 
Actual error is,

name@name:~$ show_webcams 0 1
libv4l2: error turning on stream: No space left on device
VIDIOC_STREAMON: No space left on device
OpenCV Error: Assertion failed (size.width>0 && size.height>0) in imshow, file /home/santhosh/opencv/modules/highgui/src/window.cpp, line 271
Traceback (most recent call last):
  File "/usr/local/bin/show_webcams", line 4, in <module>
    __import__('pkg_resources').run_script('StereoVision==1.0.3', 'show_webcams')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 738, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1506, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/StereoVision-1.0.3-py2.7.egg/EGG-INFO/scripts/show_webcams", line 66, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/StereoVision-1.0.3-py2.7.egg/EGG-INFO/scripts/show_webcams", line 50, in main
    
  File "build/bdist.linux-x86_64/egg/stereovision/stereo_cameras.py", line 103, in show_videos
  File "build/bdist.linux-x86_64/egg/stereovision/stereo_cameras.py", line 97, in show_frames
cv2.error: /home/santhosh/opencv/modules/highgui/src/window.cpp:271: error: (-215) size.width>0 && size.height>0 in function imshow

Ubuntu  Version : 14.04
Opencv Version: 3.0.0

**Comment by erget** [comment]
Have you tried using other device numbers?

> libv4l2: error turning on stream: No space left on device
> VIDIOC_STREAMON: No space left on device

Looks like there's a problem with the OS' access to your device itself. Maybe try

    show_webcams 1 2

just to see what happens.

**Comment by santhoshrsk** [comment]
Yes, I Tried different numbers also, still same issue. I even tried checking cam index it was 0 and 1.

name@name:~ $  ls /dev/video
/dev/video0  /dev/video1.

**Comment by rijesha** [comment]
You may have too many devices on that usb controller. try unplugging other usb devices or try to use a different usb port

**Comment by kahlju** [comment]
This could be a few things actually.  I think you should not use 3.0.0 first of all.  I don't believe that was a stable version?  I could be wrong.  Anyways.  For devices, you could have several built in webcams in which case it would be 0, 1 and so on, in this case your device would be 2 and 3 or something like that.  You said nothing about your actual device though.  Is it a singlestream camera perhaps (one chord from two cameras which projects a single stream video side by side like mine?  If so, you use the same device ID.  My case is [0 0].  The last thing it could be is your install options for opencv.  This is a pain but you have to do the research for that on your own.  Opencv options has many tutorials and I don't want to walk you through the wrong way as I am still having some issues with a functionality later on my own.
