### ISSUE TITLE
How Can I Export My Project?

### ISSUE THREAD

**Issue by mustafamertunali** [erget/StereoVision#19]
Firstly, Nice project. I really liked it. I have a little problem with this project. My code is like this:

```
import cv2
import numpy as np
from matplotlib import pyplot as plt
cap = cv2.VideoCapture(1)
cap1= cv2.VideoCapture(0)
while(1):
    	_,frame = cap.read()    
	_,f2=cap1.read()
	cv2.imshow('2', frame)
	cv2.imshow('1', f2)
	if cv2.waitKey(33)== 27:
		break
	  
cv2.destroyAllWindows()
cap.release()
```

How can use your system? How can I export your data or etc.

Have a nice day.

**Comment by erget** [comment]
There's lots of info on that here:
https://erget.wordpress.com/2014/04/27/producing-3d-point-clouds-with-a-stereo-camera-in-opencv/
