### ISSUE TITLE
Error calibrating the stereo cameras

### ISSUE THREAD

**Issue by siddhya** [erget/StereoVision#26]
I wrote a python script as suggested here: https://stackoverflow.com/a/38673008/6947737

But I am getting the following error. Any idea what is going wrong?

python rectify_image.py 
OpenCV Error: One of arguments' values is out of range (image width and height must be positive) in cvCalibrateCamera2, file /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/calib3d/src/calibration.cpp, line 1477
Traceback (most recent call last):
  File "rectify_image.py", line 16, in <module>
    calibration = calibrator.calibrate_cameras()
  File "/usr/local/lib/python2.7/dist-packages/stereovision/calibration.py", line 241, in calibrate_cameras
    flags=flags)[1:]
cv2.error: /build/opencv-SviWsf/opencv-2.4.9.1+dfsg/modules/calib3d/src/calibration.cpp:1477: error: (-211) image width and height must be positive in function cvCalibrateCamera2

**Comment by callmeB** [comment]
As already mentioned #16 change your stereoCalibration arguments according to your OpenCV version in
`/usr/local/lib/python2.7/dist-packages/stereovision/calibration.py`

**Comment by erget** [comment]
Thanks @callmeB !
