### ISSUE TITLE
Where are .ply files saved?

### ISSUE THREAD

**Issue by annacesar** [erget/StereoVision#29]
Hi,
I cannot locate the ply file created with:
from stereovision.point_cloud import PointCloud
foo = PointCloud(points, colors)

if I type foo in the console I get:
<stereovision.point_cloud.PointCloud at 0xea20078390>

 I have also opened your original code, but I cannot find the path in which the .ply are saved.
May you help me with this issue?

Thanks
anna

**Comment by erget** [comment]
Hi Anna,

For this you'll need to use the [`write_ply`](https://github.com/erget/StereoVision/blob/1adff45e291362f52188e0fd0211265845a4461a/stereovision/point_cloud.py#L61). It'll save to a path relative to your current working directory, or to an absolute path.
