### ISSUE TITLE
Could you update the project to opencv newer version(2.4.1 or 3.0)

### ISSUE THREAD

**Issue by Soulskater** [erget/StereoVision#3]
I tried to update it locally and i got no errors but the mashlab could not open my generated .ply file.

**Comment by erget** [comment]
Okay. Could you specify the error more precisely? Also, a pull request with the updated code would give me a chance to look into it a bit more. Sadly, I don't have the hardware setup in place at the moment that I would need to really test things out but if you send a few test images I could work with that.

**Comment by Soulskater** [comment]
Sorry finally i loaded my ply file into meshlab but it look pretty weird, also i checked the disparity map and rectified images and those are look bad i think.(i'm quite new in image processing)
So i forked your repo and committed my changes and an images folder for testing, where you can find my calibration images(images/calib), and source files(images/src), and my test results(images/test_result).
Thanks for your help
