### ISSUE TITLE
int concatenate issue

### ISSUE THREAD

**Issue by wuxiaohua1011** [erget/StereoVision#35]
on line 86 and 87 in stereo_camera.py, the code
`left_frame = frame[:, : width/2, :]` and `right_frame = frame[:, width/2:, :]` should be  
`left_frame = frame[:, :int(width/2), :]` and  `right_frame = frame[:, int(width/2):, :]` 

i have Macbook Pro and its reporting 
`TypeError: slice indices must be integers or None or have an __index__ method` without those

**Comment by erget** [comment]
Seems reasonable. Would you like to send a PR that implements this? This might also be a Python2 vs Python3 issue, as Python2 probably implicitly casts floats...
