### ISSUE TITLE
Calibration Format

### ISSUE THREAD

**Issue by DapperFactory** [erget/StereoVision#4]
Hey thanks for the library. 

If already have the calibration matrix for my camera, how do I need to format it so images_to_pointcloud will work. 

Thanks!

**Comment by erget** [comment]
They're formated as numpy exports. Take a look at [this code](https://github.com/erget/StereoVision/blob/master/stereovision/calibration.py#L67-L75) for an example - all ``dict`` instances in the ``StereoCalibration`` object are saved using numpy formatting and filename ``{key}_{rig_side}.npy``.
