### ISSUE TITLE
Single USB synchronized stereo camera returns  TypeError: slice indices must be integers or None or have an __index__ method.

### ISSUE THREAD

**Issue by Jgil10** [erget/StereoVision#42]
I am running Python 3.7 and using a single USB synchronized stereo camera delivering side by side images in single frames.  I set devices to 0 0 to indicate both frames come from the same camera. 

In stereo_cameras.py the function get_frames_singleimage is supposed to slice the single frame into a left and right frame. It returns the error:

Library code:
left_frame = frame[:, :width/2, :]
TypeError: slice indices must be integers or None or have an __index__ method.

The code works properly if changed to make width an integer as below.
left_frame = frame[:, :int(width / 2), :]
right_frame = frame[:, int(width / 2):, :]

**Comment by erget** [comment]
Hi @Jgil10 , thanks for pointing this out. Would you be willing to put this into a PR that I can incorporate into an update for other users?

**Comment by Jgil10** [comment]
Hi as I am new to github I have never done a pull request or programmed using a formal change control system.I am a hobbyist and will need to read a lot to understand the procedure.Sent on my Boost Mobile Samsung Galaxy S8.
-------- Original message --------From: Daniel Lee <notifications@github.com> Date: 11/30/20  3:44 AM  (GMT-05:00) To: erget/StereoVision <StereoVision@noreply.github.com> Cc: Jgil10 <jgil1048@comcast.net>, Mention <mention@noreply.github.com> Subject: Re: [erget/StereoVision] Single USB synchronized stereo camera
  returns  TypeError: slice indices must be integers or None or have an
  __index__ method. (#42) 
Hi @Jgil10 , thanks for pointing this out. Would you be willing to put this into a PR that I can incorporate into an update for other users?

**Comment by erget** [comment]
Hi @Jgil10 , it's really very easy and should only take 10 minutes - GitHub has some great tutorials on this subject. I leave it up to you - thanks for getting in touch :)

**Comment by Jgil10** [comment]
Thanks for the reply. I am new to github and have no repositories. I modified my installed StereoVision library to test the fix and it worked fine.The two lines of code changed as I describe work fine. Just make the width variable an integer. In the two lines.Sent on my Boost Mobile Samsung Galaxy S8.
-------- Original message --------From: Daniel Lee <notifications@github.com> Date: 11/30/20  3:44 AM  (GMT-05:00) To: erget/StereoVision <StereoVision@noreply.github.com> Cc: Jgil10 <jgil1048@comcast.net>, Mention <mention@noreply.github.com> Subject: Re: [erget/StereoVision] Single USB synchronized stereo camera
  returns  TypeError: slice indices must be integers or None or have an
  __index__ method. (#42) 
Hi @Jgil10 , thanks for pointing this out. Would you be willing to put this into a PR that I can incorporate into an update for other users?
