### ISSUE TITLE
error

### ISSUE THREAD

**Issue by b4zz4** [erget/StereoVision#5]
./show_webcams 
Traceback (most recent call last):
  File "./show_webcams", line 25, in <module>
    from stereovision.stereo_cameras import StereoPair
ImportError: No module named stereovision.stereo_cameras

**Comment by erget** [comment]
It looks like you haven't installed the library before trying to execute ``show_webcams``. Since this issue is lacking any kind of context I'm closing it. Feel free to reopen it with a description if this doesn't help.

**Comment by b4zz4** [comment]
I install the library.
